version: '3'

services:
    api:
        container_name: ${COMPOSE_PROJECT_NAME}-api
        platform: linux/amd64
        image: astrotechdevs/php-nginx:latest
        working_dir: /app
        ports:
            - '8038:80'
        volumes:
            - ./:/app
            - ./.docker/crontab:/etc/cron.d/custom-crontab
            - ./.docker/consumer/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
        networks:
            - ${COMPOSE_PROJECT_NAME}-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        container_name: ${COMPOSE_PROJECT_NAME}-mariadb
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--wait_timeout=28800',
            '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            '--sort_buffer_size=50485760' # 10MB
        ]
        restart: always
        ports:
            - "33897:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        networks:
            - ${COMPOSE_PROJECT_NAME}-network
        volumes:
            - ./.docker/data:/var/lib/mysql

    redis:
        image: redis:6.2.6
        platform: linux/amd64
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./.docker/redis:/data
        networks:
            - ${COMPOSE_PROJECT_NAME}-network
        depends_on:
            - api

networks:
    maps-crud-network:
        driver: bridge
